# Generated by Django 4.2.7 on 2023-11-24 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_sala', models.CharField(max_length=30)),
                ('local', models.CharField(choices=[('UABJ', 'UABJ'), ('AEB', 'AEB')], default='UABJ', max_length=4)),
                ('reservado', models.BooleanField(default=False)),
                ('quem_reservou', models.CharField(max_length=30)),
                ('data_reserva', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('data_solicitacao', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
