# Generated by Django 4.2.7 on 2023-11-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salas',
            options={'verbose_name': 'Sala'},
        ),
        migrations.AddField(
            model_name='salas',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
