# Generated by Django 4.2.7 on 2023-11-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_alter_salas_options_salas_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salas',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
