# Generated by Django 4.2.7 on 2023-12-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('salas', '0004_remove_salas_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='data_devolucao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salas',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
