# Generated by Django 4.2.7 on 2023-12-01 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('salas', '0006_remove_salas_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='quem_reservou',
        ),
        migrations.AddField(
            model_name='reservas',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
