# Generated by Django 4.2.7 on 2023-12-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('salas', '0007_remove_reservas_quem_reservou_reservas_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='usuarios',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
