# Generated by Django 4.2.7 on 2023-12-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_alter_reservas_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
