# Generated by Django 4.2.7 on 2023-12-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0009_alter_reservas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
