# Generated by Django 4.2.7 on 2023-12-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0010_alter_reservas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='devolvida',
            field=models.BooleanField(default=False),
        ),
    ]
