# Generated by Django 4.2.7 on 2023-12-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0011_salas_devolvida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='devolvida',
        ),
    ]
