# Generated by Django 4.2.7 on 2024-02-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0012_remove_salas_devolvida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='data_devolucao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_reserva',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
