# Generated by Django 4.2.7 on 2024-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
